<?php
// Remove inline styles generated by the native WordPress gallery
add_filter('gallery_style', 'chip_no_gallery_style', 99);
function chip_no_gallery_style() {
	return '<div class="gallery">';
}

// remove stuff from header for HTML5 conformance
add_action('init', 'conformanceRemoval');

function conformanceRemoval() {
	remove_action('wp_head', 'rsd_link');
	remove_action('wp_head', 'wlwmanifest_link');
	remove_action('wp_head', 'wp_generator');

	remove_action('wp_head', 'feed_links_extra', 3); // Display the links to the extra feeds such as category feeds
	remove_action('wp_head', 'feed_links', 2); // Display the links to the general feeds: Post and Comment Feed
	remove_action('wp_head', 'index_rel_link'); // index link
	remove_action('wp_head', 'parent_post_rel_link', 10, 0); // prev link
	remove_action('wp_head', 'start_post_rel_link', 10, 0); // start link
	remove_action('wp_head', 'adjacent_posts_rel_link', 10, 0); // Display relational links for the posts adjacent to the current post.
}
?>
