<?php
// Remove inline styles generated by the native WordPress gallery
add_filter('gallery_style', 'chip_no_gallery_style', 99);
function chip_no_gallery_style() {
	return '<div class="gallery">';
}
?>
